---
title: "species lists"
author: "TG"
date: "2 1 2022"
output:
   prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(stringr)
library(Hmisc)
library(vegan)
library(mobr)
library(lme4)
library(lmerTest)
library(MuMIn)
library(Rarefy)
library(rareNMtests)
```

```{r}
load("fish_full_data.rdata")

```


1) set one observer

```{r}
one_observer<-list()
loop<-1
set.seed(1)
for (i in unique(fish_full_data$survey_id)) {
  
  data <- fish_full_data %>% filter(survey_id == i)
  
  obs_amount <- length(unique(data$Observer))
  obs_name <- unique(data$Observer)
  chosen_obs <- sample(obs_name,1)  
 
  filter_data<-data %>% filter(Observer == chosen_obs)
  one_observer[[loop]]<-filter_data
  loop<-loop+1
  
  
}

one_observer<- bind_rows(one_observer)

rm(data,filter_data)
```


2) filter confidence = 1

for the years 2015-2017 where there is no confidance value i set the value 0

```{r}

one_observer$Confidence[is.na(one_observer$Confidence)]<-(0)
one_observer<-one_observer %>% filter(Confidence < 1)

```

3) filter the north beach
```{r}
one_observer<-one_observer %>%
  filter(Site !="North beach",
         ! Knoll %in% c("Tamar","South bridge reserve","south bridge reserve",
                        "North bridge reserve","north bridge reserve"))
                                      
```



4) add the month to the sample

```{r include=FALSE}

one_observer$year_month<-ifelse(month(one_observer$Date)>6,
                                paste(one_observer$Year,"b",sep= " "),
                                paste(one_observer$Year,"a",sep= " "))


```

#one observer species list


##Species list 2018

```{r}
species_list_2018 <- one_observer %>%
  filter(Year == "2018") %>% 
  group_by(Species) %>% summarise("abundance_2018"=sum(Abundance))
  
```


##Species list 2021

```{r}
species_list_2021 <- one_observer %>%
  filter(Year == "2021") %>% 
  group_by(Species) %>% summarise("abundance_2021"=sum(Abundance))
```

```{r}

both_list<-full_join(species_list_2018,species_list_2021)


both_list$abundance_2018[is.na(both_list$abundance_2018)]<-0

both_list$abundance_2021[is.na(both_list$abundance_2021)]<-0

```

# species list with second observer addition 

add only missing species but don't tampre with abundases of existing species



```{r}
full_data_clean<-fish_full_data
  
full_data_clean$Confidence[is.na(full_data_clean$Confidence)]<-(0)
full_data_clean<-full_data_clean %>% filter(Confidence < 1)


full_data_clean<-full_data_clean %>%
  filter(Site !="North beach",
         ! Knoll %in% c("Tamar","South bridge reserve","south bridge reserve",
                        "North bridge reserve","north bridge reserve"))
                                      
full_data_clean$year_month<-ifelse(month(full_data_clean$Date)>6,
                                paste(full_data_clean$Year,"b",sep= " "),
                                paste(full_data_clean$Year,"a",sep= " "))

```



```{r}
full_clean_2018<-full_data_clean %>%
  filter(Year =="2018") %>% 
  group_by(Species) %>%
  summarise(abundance_2018=sum(Abundance)) %>% 
  filter(!Species %in% species_list_2018$Species)

full_clean_2018<-bind_rows(species_list_2018,full_clean_2018)
```



```{r}
full_clean_2021<-full_data_clean %>%
  filter(Year =="2021") %>% 
  group_by(Species) %>%
  summarise(abundance_2021=sum(Abundance)) %>% 
  filter(!Species %in% species_list_2021$Species)

full_clean_2021<-bind_rows(species_list_2021,full_clean_2021)
```


```{r}

both_list_full<-full_join(full_clean_2018,full_clean_2021)


both_list_full$abundance_2018[is.na(both_list_full$abundance_2018)]<-0

both_list_full$abundance_2021[is.na(both_list_full$abundance_2021)]<-0

write.csv(both_list_full,"species_list_2018_2021.csv")

```

